export const Chatt_User1 = [
  {
    name: 'Ngadiyo',
    image: 'https://robohash.org/eligendieumfugit.png?size=50x50&set=set1',
    time: '08:00 AM',
    message: 'Astaga, Lu ngapain Ege How Are You Body?',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Ngatmo',
    image: 'https://robohash.org/minimavoluptasvelit.png?size=50x50&set=set1',
    time: '05:30 AM',
    message: 'Can You Help Me?',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Ngadio',
    image: 'https://robohash.org/nihilquoqui.png?size=50x50&set=set1',
    time: '04:45 PM',
    message: 'wkwkwkw, You Crazy?',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Paiman',
    image: 'https://robohash.org/delenitiquiaaperiam.png?size=50x50&set=set1',
    time: '11:30 AM',
    message: 'Im Bored?',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Temon',
    image: 'https://robohash.org/mollitiaquiat.png?size=50x50&set=set1',
    time: '09:00 AM',
    message: 'ckckckckckckckckckc',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'judio',
    image: 'https://robohash.org/quiautqui.png?size=50x50&set=set1',
    time: '07:15 AM',
    message: 'Photo',
    icon: 'image',
    messageType: 'Photo',
  },
  {
    name: 'suratman',
    image:
      'https://robohash.org/corruptitemporibuslibero.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Purwanto',
    image: 'https://robohash.org/consequaturautea.png?size=50x50&set=set1',
    time: '00:50 PM',
    message: 'Astaga, Lu ngapain Ege',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Surip',
    image: 'https://robohash.org/magnamaccusamusmaxime.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Bagong',
    image: 'https://robohash.org/velitquiaqui.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Purwadiyo',
    image: 'https://robohash.org/velmaximealiquam.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Bendel',
    image:
      'https://robohash.org/corruptitemporibuslibero.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Paijo',
    image:
      'https://robohash.org/corruptitemporibuslibero.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Sujati',
    image:
      'https://robohash.org/corruptitemporibuslibero.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Parman',
    image:
      'https://robohash.org/corruptitemporibuslibero.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Sulastri',
    image:
      'https://robohash.org/corruptitemporibuslibero.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
];

export const Chatt_User2 = [
  {
    name: 'Jhonson',
    image: 'https://robohash.org/magnamaccusamusmaxime.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Lylia',
    image: 'https://robohash.org/velitquiaqui.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Lyla',
    image: 'https://robohash.org/velmaximealiquam.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Hanabi',
    image:
      'https://robohash.org/corruptitemporibuslibero.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Freya',
    image:
      'https://robohash.org/corruptitemporibuslibero.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Tigreal',
    image:
      'https://robohash.org/corruptitemporibuslibero.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Balmond',
    image:
      'https://robohash.org/corruptitemporibuslibero.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Barats',
    image:
      'https://robohash.org/corruptitemporibuslibero.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Guinivera',
    image: 'https://robohash.org/eligendieumfugit.png?size=50x50&set=set1',
    time: '08:00 AM',
    message: 'Astaga, Lu ngapain Ege How Are You Body?',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Alucard',
    image: 'https://robohash.org/minimavoluptasvelit.png?size=50x50&set=set1',
    time: '05:30 AM',
    message: 'Can You Help Me?',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Angela',
    image: 'https://robohash.org/nihilquoqui.png?size=50x50&set=set1',
    time: '04:45 PM',
    message: 'wkwkwkw, You Crazy?',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Alexander',
    image: 'https://robohash.org/delenitiquiaaperiam.png?size=50x50&set=set1',
    time: '11:30 AM',
    message: 'Im Bored?',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Newton',
    image: 'https://robohash.org/mollitiaquiat.png?size=50x50&set=set1',
    time: '09:00 AM',
    message: 'ckckckckckckckckckc',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Bell',
    image: 'https://robohash.org/quiautqui.png?size=50x50&set=set1',
    time: '07:15 AM',
    message: 'Photo',
    icon: 'image',
    messageType: 'Photo',
  },
  {
    name: 'Isaac',
    image:
      'https://robohash.org/corruptitemporibuslibero.png?size=50x50&set=set1',
    time: '00:11 PM',
    message: 'Lol Banget dah wkwkwkwkwk',
    icon: 'image',
    messageType: 'text',
  },
  {
    name: 'Edishon',
    image: 'https://robohash.org/consequaturautea.png?size=50x50&set=set1',
    time: '00:50 PM',
    message: 'Astaga, Lu ngapain Ege',
    icon: 'image',
    messageType: 'text',
  },
];
