export const Panggilan_User1 = [
  {
    name: 'Paijo',
    image: 'https://robohash.org/eligendieumfugit.png?size=50x50&set=set1',
    date: 'Jan 01',
    time: '01:03 AM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Ngadiman',
    image: 'https://robohash.org/minimavoluptasvelit.png?size=50x50&set=set1',
    date: 'Yesterday',
    time: '01:03 PM',
    callType: 'call',
    call: 'call-received',
  },
  {
    name: 'Tukiyem',
    image: 'https://robohash.org/nihilquoqui.png?size=50x50&set=set1',
    date: 'Today',
    time: '04:00 AM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Paiman',
    image: 'https://robohash.org/delenitiquiaaperiam.png?size=50x50&set=set1',
    date: 'Jan 15',
    time: '05:50 PM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Mbok de Piyah',
    image: 'https://robohash.org/mollitiaquiat.png?size=50x50&set=set1',
    date: 'Jan 16',
    time: '06:50 PM',
    callType: 'video-call',
    call: 'call-missed',
  },
  {
    name: 'Bledes',
    image: 'https://robohash.org/quiautqui.png?size=50x50&set=set1',
    date: 'Jan 01',
    time: '02:22 PM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Parmin',
    image: 'https://robohash.org/consequaturautea.png?size=50x50&set=set1',
    date: 'Feb 15',
    time: '09:50 AM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Tukiyem',
    image: 'https://robohash.org/magnamaccusamusmaxime.png?size=50x50&set=set1',
    date: 'Feb 14',
    time: '01:03 AM',
    callType: 'call',
    call: 'call-received',
  },
  {
    name: 'Ngatinem',
    image: 'https://robohash.org/velitquiaqui.png?size=50x50&set=set1',
    date: 'Feb 22',
    time: '04:00 PM',
    callType: 'video-call',
    call: 'call-received',
  },
  {
    name: 'Sri',
    image: 'https://robohash.org/velmaximealiquam.png?size=50x50&set=set1',
    date: 'Feb 21',
    time: '01:12 AM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Paryati',
    image: 'https://robohash.org/autnequevel.png?size=50x50&set=set1',
    date: 'Feb 10',
    time: '09:50 AM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Sujatmi',
    image: 'https://robohash.org/consequaturautea.png?size=50x50&set=set1',
    date: 'Feb 5',
    time: '01:00 PM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Temon',
    image: 'https://robohash.org/consequaturautea.png?size=50x50&set=set1',
    date: 'Feb 5',
    time: '01:00 PM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Kucrut',
    image: 'https://robohash.org/consequaturautea.png?size=50x50&set=set1',
    date: 'Feb 5',
    time: '01:00 PM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Ngadiyo',
    image: 'https://robohash.org/consequaturautea.png?size=50x50&set=set1',
    date: 'Feb 5',
    time: '01:00 PM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Ngatmo',
    image: 'https://robohash.org/consequaturautea.png?size=50x50&set=set1',
    date: 'Feb 5',
    time: '07:00',
    callType: 'call',
    call: 'call-missed',
  },
];

export const Panggilan_User2 = [
  {
    name: 'Leonardo',
    image: 'https://robohash.org/velitquiaqui.png?size=50x50&set=set1',
    date: 'Feb 22',
    time: '04:00 PM',
    callType: 'video-call',
    call: 'call-received',
  },
  {
    name: 'Einstein',
    image: 'https://robohash.org/velmaximealiquam.png?size=50x50&set=set1',
    date: 'Feb 21',
    time: '01:12 AM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Galileo',
    image: 'https://robohash.org/autnequevel.png?size=50x50&set=set1',
    date: 'Feb 10',
    time: '09:50 AM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Alva',
    image: 'https://robohash.org/consequaturautea.png?size=50x50&set=set1',
    date: 'Feb 5',
    time: '01:00 PM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Galilei',
    image: 'https://robohash.org/consequaturautea.png?size=50x50&set=set1',
    date: 'Feb 5',
    time: '01:00 PM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Edishon',
    image: 'https://robohash.org/consequaturautea.png?size=50x50&set=set1',
    date: 'Feb 5',
    time: '01:00 PM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Thomas',
    image: 'https://robohash.org/consequaturautea.png?size=50x50&set=set1',
    date: 'Feb 5',
    time: '01:00 PM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Newton',
    image: 'https://robohash.org/consequaturautea.png?size=50x50&set=set1',
    date: 'Feb 5',
    time: '07:00',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Alexander',
    image: 'https://robohash.org/eligendieumfugit.png?size=50x50&set=set1',
    date: 'Jan 01',
    time: '01:03 AM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Zilong',
    image: 'https://robohash.org/minimavoluptasvelit.png?size=50x50&set=set1',
    date: 'Yesterday',
    time: '01:03 PM',
    callType: 'call',
    call: 'call-received',
  },
  {
    name: 'Angela',
    image: 'https://robohash.org/nihilquoqui.png?size=50x50&set=set1',
    date: 'Today',
    time: '04:00 AM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Selena',
    image: 'https://robohash.org/delenitiquiaaperiam.png?size=50x50&set=set1',
    date: 'Jan 15',
    time: '05:50 PM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Balmond',
    image: 'https://robohash.org/mollitiaquiat.png?size=50x50&set=set1',
    date: 'Jan 16',
    time: '06:50 PM',
    callType: 'video-call',
    call: 'call-missed',
  },
  {
    name: 'Saber',
    image: 'https://robohash.org/quiautqui.png?size=50x50&set=set1',
    date: 'Jan 01',
    time: '02:22 PM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Freya',
    image: 'https://robohash.org/consequaturautea.png?size=50x50&set=set1',
    date: 'Feb 15',
    time: '09:50 AM',
    callType: 'call',
    call: 'call-missed',
  },
  {
    name: 'Lyla',
    image: 'https://robohash.org/magnamaccusamusmaxime.png?size=50x50&set=set1',
    date: 'Feb 14',
    time: '01:03 AM',
    callType: 'call',
    call: 'call-received',
  },
];
